---
sidebar: sidebar 
permalink: task-manage-private-aws.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, aws 
summary: 在 AWS Marketplace 入口網站中接受 NetApp Console 的 Marketplace 私有報價，並在 Console 中設定 AWS 憑證。 
---
= 接受並配置NetApp Console的 AWS Marketplace 專屬優惠
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 AWS Marketplace 入口網站中接受 NetApp Console 的 Marketplace 私有報價，並在 Console 中設定 AWS 憑證。

.開始之前
* 與NetApp銷售人員合作創建私人優惠並取得啟動連結。
* 確保您擁有所需的 AWS Marketplace 權限：
+
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers-subscribing.html["查看並訂閱專屬優惠"]
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groups-policies.html["買家權限驗證"]






== 接受 AWS Marketplace Portal 中的私有優惠

需要在控制台中完成訂閱分配才能啟動購買並套用折扣價格。


NOTE: 您必須完成所有步驟才能啟動您的專屬優惠。跳過任何步驟都可能導致帳單錯誤。多次接受並啟動優惠可能會導致重複收費。

.步驟
. 從您的 NetApp 銷售團隊選取私人優惠啟動連結。
+
該連結應類似於以下內容： `https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`

+
如果您未收到連結，請在 AWS Marketplace 主控台中檢視私有優惠。需要下列權限：

+
** 使用 AWS 託管策略：*AWSMarketplaceRead-only*、*AWSMarketplaceManageSubscriptions* 或 *AWSMarketplaceFullAccess*
** 使用自訂 IAM 策略： `aws-marketplace:ListPrivateListings`和 `aws-marketplace:ViewSubscriptions`


. 您將被重定向到 AWS Marketplace 來查看專屬優惠。
+

NOTE: 私人報價是在公開清單的基礎上建立的。使用「*優惠選擇*」下拉式選單在公開優惠和私人優惠之間切換。

. 查看私人優惠詳情並確認其符合您的協議。如果不正確，請不要接受。聯絡您的NetApp客戶團隊。
+
[NOTE]
====
私人優惠有兩種類型：

** *按需使用*
+
*** 定價訊息
*** 法律條款


** *合約*
+
*** 持續時間和日期
*** 續訂設定
*** 合約選項
*** 合約總價




對於合約報價，請輸入約定的單位數。對於Cloud Volumes ONTAP，請確保在訂閱之前選擇正確的授權。

====
. 若要接受私人優惠，請執行以下操作：
+
.. 如需隨需使用，請選擇 *Subscribe* 。
.. 對於合約報價，請輸入每項服務的單位數量，然後選取 *Create contract* 。


. 接受後，橫幅會確認訂閱並提供註冊說明。
. 選擇 *Set up your account* 。這將重新導向至 NetApp Console 以設定訂閱。
+
[NOTE]
====
如果您接受了報價但尚未完成註冊，請返回產品頁面。對於合約商品，請選擇 *View purchase options* 以顯示報價，然後選擇 *Set up your account*。

====
. Sign in 於  https://console.netapp.com[]。
. 登入後，導航至 https://console.netapp.com/licenses/overview[]。系統將提示您：
+
.. 輸入 Marketplace 訂閱的「顯示名稱」。
.. 選擇擁有訂閱存取權限的 Console *組織*。
.. [可選] 啟用 *Replace existing subscription* 以覆蓋組織的現有訂閱。
+
[NOTE]
====
*** 替換僅適用於一個控制台帳戶。
*** 若要將多個帳戶與相同訂閱關聯，請手動設定其他帳戶。
*** 如果憑證從未與訂閱關聯，請按下一節所述手動關聯它們。


====


. 選擇 **Associate**。
. 填寫表格，將訂閱與您的 Console 組織建立關聯。選擇 **Associate** 。
. 關聯訂閱後，請選取 **Billing preferences** 標籤。
. 查看應用程式商店的訂閱選項。
. 選擇您要計費的商城訂閱服務。這僅適用於存在多個選項的情況。
. 選擇**儲存變更**。
. 如果有多個雲端供應商的多個訂閱，請視需要重複這些步驟。


有關市場訂閱和直接許可計費的更多信息，請參閱 link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["帳單偏好文檔"]。
