---
sidebar: sidebar 
permalink: task-homepage.html 
keywords: license, licensing, dashboard, capacity license, capacity based license, add license, install license, bluexp, netapp console, cloud volumes ontap license, cloud volumes ontap 
summary: 在控制台的概覽儀表板上取得您組織的所有訂閱和許可證的概覽。 
---
= 使用儀表板概覽
:allow-uri-read: 




== 使用儀表板概覽

[role="lead"]
NetApp Console 中的 *Overview* 儀表板可協助您監控 Licenses and subscriptions 的狀態，確保您能在訂閱到期日或容量限制時管理成本並維持服務。

您可以查看有關每個資料服務 （包括 Cloud Volumes ONTAP） 的特定授權和訂閱資訊。

Licenses and subscriptions 儀表板會在容量限制或到期時發出警報，提示您採取必要的措施。



=== 查看特定數據服務的詳細信息

*Overview* 儀表板提供以下服務的詳細資訊：

* 備份和復原
* 雲端分層
* Cloud Volumes ONTAP
* 災難復原
* 勒索軟體抵禦能力


例如，負責管理Cloud Volumes ONTAP資源的管理員可以查看每個授權或訂閱的目前容量，從而使他們能夠集中查看其權限範圍內的資源。


NOTE: 雖然您可以從儀表板更新和刪除許可證，但您不能新增新的許可證或訂閱。

link:task-manage-data-services-licenses.html["了解有關管理許可證的詳細信息"].link:task-manage-subscriptions.html["了解有關管理訂閱的更多信息"].

.步驟
. 從NetApp Console選單中，選擇「管理 >Licenses and subscriptions」。
. 選擇*概覽*。
. 選擇對應資料服務（包括Cloud Volumes ONTAP）的「檢視」以查看詳細資訊並管理授權和訂閱。
+
每個圖塊都提供了容量的圖形概覽。您可以查看詳細資訊頁面以查看和管理該容量的付款方式。

. 選擇“*許可證*”或“*訂閱*”選項卡。
. 透過選擇列過濾器和要過濾的值來過濾表格。例如，在「*訂閱*」標籤上，您可以按年度合約或訂閱過濾「類型」列。
. 自訂表中顯示的列。您可以透過選擇「*列*」圖示來指示要顯示或隱藏哪些列，從而在表中新增和刪除列。
. 展開任意行即可查看訂閱或授權所包含的內容、購買的容量和條款的詳細資訊。
. 使用操作選單來管理特定的授權或訂閱，例如更新授權或將訂閱與其他組織關聯。
+
您無法從特定服務的 *Overview* 頁面新增新的 licenses 或 subscriptions。您只能從 *Direct licenses* 標籤新增 licenses，或從 *Marketplace subscriptions* 標籤新增 subscriptions。

+
link:task-manage-data-services-licenses.html["了解有關管理許可證的更多資訊。"] link:task-manage-subscriptions.html["了解有關管理訂閱的更多資訊。"]





=== 解決授權或訂閱問題

在概覽儀表板中，您可以查看需要解決的 Licenses and subscriptions 問題。這些問題包括即將到期或已達到容量上限的 Licenses and subscriptions。

. 從NetApp Console選單中，選擇「管理 >Licenses and subscriptions」。
. 選擇*概覽*。
. 在 *Requires action* 磚貼中，選取 *Resolve* 以檢視需要調整的問題。如果未顯示 *Resolve*，則表示沒有需要操作的問題。
. 從「需要操作」頁面中，選擇「授權」標籤或「訂閱」標籤。
. 使用操作選單來解決問題。
+
link:task-manage-data-services-licenses.html["了解有關管理許可證的詳細信息"].link:task-manage-subscriptions.html["了解有關管理訂閱的更多信息"].


